### ISSUE TITLE
L.Marker.setIcon() in click handler shifts popup anchor

### ISSUE THREAD

**Issue by BKGiser** [Leaflet/Leaflet#4026]
Hi
    I have maker bind a popup,but I use setIcon() function ,find popup offset was changed,question at Layer.Popup.js, line:30,why not add judge.

**Comment by IvanSanchez** [comment]
Sorry, @BKGiser, but I don't understand the question.

**Comment by BKGiser** [comment]
var marker = new L.Marker({lat:40,lng:40});	
  marker.addTo(map); 
  marker .on("click", function (e) {
            e.target.setIcon(this.overStyle);
        }, context)

Click on the marker,popup window's offset will be changed,my expression may not be good.I so sorry too.

**Comment by IvanSanchez** [comment]
OK, I think I understand. Just changing the marker's icon moves the popup's **anchor**, but this only happens if the icon is changed on the `click` event handler.

This can be worked out by manually adding the popup to the map in the `click` event handler instead of using `bindPopup`, I guess.

**Comment by wvq** [comment]
I found the bug cause at Layer._popupAnchor(), it adds new offset to original, not replace!
So, if you want to change icon, just change it but don't set popupAnchor again, or you will get a new offset by (old popupAnchor + new popupAnchor)

**Comment by ghybs** [comment]
For reference, these are currently lines [30](https://github.com/Leaflet/Leaflet/blob/master/src/layer/Layer.Popup.js#L30) and [147](https://github.com/Leaflet/Leaflet/blob/master/src/layer/Layer.Popup.js#L147) of `Layer.Popup.js`, introduced by commit https://github.com/Leaflet/Leaflet/commit/6bf0f98796abecba05943e5dc7c5c2896d611568.

Still not sure what was the original intended behaviour of that code?

**Comment by mourner** [comment]
@yohanboniface was this fixed by the recent popup improvements by chance?

**Comment by ghybs** [comment]
Hi,

Looks like this bug no longer occurs in Leaflet 1.0.0-rc.2: http://plnkr.co/edit/roYxw2ts8yTufltTnS4T?p=preview

The "faulty" code has been removed indeed, which also removed the `offset` option of `L.Popup`.
Still do not know what was the objective of that option though…

**Comment by yohanboniface** [comment]
Cool, thanks for checking with rc2 :)
Closing then.

**Comment by nemo3000** [comment]
I'm using 1.7.1 but I have same issue, when I use setIcon, new icon change position, if I use same comand to restore previus icon cursor return to correct position.

**Comment by Falke-Design** [comment]
@nemo3000 can you please create a demo: leafletjs.com/edit.html
