### ISSUE TITLE
Invisible vector layers on SVG Renderer after Renderer is removed then re-added on map

### ISSUE THREAD

**Issue by abigaildelarosa** [Leaflet/Leaflet#5960]
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome 62.0.3202.62 (tried with firefox and it does the same)
- OS/Platform (with version) I'm using: Ubuntu 16.04
- step 1
- step 2
Application summary:
I do have several geoJson files. I want to create buttons/links to select which file should be use. When the user click the button/link then a specific geoJson file will be display. Once the file is displayed several layers out of the file are created and then the user can select which layer does he needs to use.

## What behaviour I'm expecting and which behaviour I'm seeing
I am expecting to see the layers. Unfortunately the layers do not show. I checked the code, the dots are there but it seems that there is no color, but when I resize the window then the layers show in the map. 

## Minimal example reproducing the issue

*The javascript looks something similar like this:
As it appears in the documentation I am creating a map, then add to it a base layer. Then I create a layer control with the baselayer. 

var map = L.map('map');
      map.setView([40.703312, -73.97968], 10);
      var baselayer_1 = L.esri.basemapLayer('Topographic');
      baselayer_1.addTo(map);
      var baseLayer = {
          "Waiting for Selection": baselayer_1
      };
      layercontrol = L.control.layers(baseLayer).addTo(map);

Then in other function "multiple layers"(assume that I have another funciton to create layer), I create the layers out of the geoFile, with a specific color depending of x category.
baselayer_1.addTo(map);
layer_1 = createlayer(geoFile, "category for color in layer");
layer_2 = createlayer(geoFile, "category for color in layer");
allLayers = {
            "one": layer_1,
            "two": layer_2,
        };
layercontrol = L.control.layers(allLayers).addTo(map);

*On the onclick event button I do have something like:
1.- remove first all the layers from the map (because we might have layers from other geoFile)
2.- then remove old control.
3.- call the function to run multiple layers and load it.
<a href="#" onclick="map.eachLayer(function(layer){map.removeLayer(layer)});
    map.removeControl(layercontrol);
    displayDotsTest(geoFile1);
     ">geoFile1</a>

Overall the button/link, is just cleaning the layers from the map, creating new layers and loading the new layers with its layercontrol each time that you select a different geoJson file. As you can see in the gift It is working for the first time, but when I click for the second time the layers do not load properly. The dots are there, but they look kind of "transparent" if I resize the window then the layers show properly. 

Things that I tried:
1.- map.invalidateSize(); (added to onclick event after calling displayDotsTest())
2.  map.invalidateSize(true); (added to onclick event after calling displayDotsTest())
3.  map.invalidateSize(false); (added to onclick event after calling displayDotsTest())
       
Currently I am trying to deal with the issue playing around with the div object and resizing dynamically the map each time that a user clicks the button, but I do find it quite dirty. 

Will be nice if you can provide some information about this issue. 

![leafletbug](https://user-images.githubusercontent.com/25774188/33831019-b697a7b2-de76-11e7-9424-8c4b0a5fb77e.gif)

**Comment by abigaildelarosa** [comment]
As you mentioned above yes I tried the invalidateSize with the timeout, with no results. As you said, is true, there is no reason to redraw the map, however if I do not do it and play around with the resizing. It does not load the layers. As I said, I deal with the issue by using a function to play around with the size, but still found it dirty. 

I think that a matter of clear layers and load layers, should be just clear and load, there is no need to play around with extra methods to get what you need. Thus I create the issue, indeed I found it part of the technical debt that should be fixed.

**Comment by ghybs** [comment]
Hi,

I apologize, it is still not clear to me whether you think there is an issue in Leaflet or in your app.

In the former case, please provide a minimal example reproducing the issue, so that we can investigate and hopefully fix it.

In any case, you can look for help on Stack Overflow, I know there is much more people that can help over there. You will still need to provide enough code though for people to be able to understand your issue. They might also help in pointing out whether the issue comes from Leaflet or your app.

**Comment by ghybs** [comment]
Hi,

I do not know if this is you, someone from your team, or a totally different person, but this question popped up on Stack Overflow and it looks really similar to your issue:
https://stackoverflow.com/questions/47823899/leaflet-changing-all-layers

The question _does_ include a live reproduction example, which makes it much easier to investigate :smiley: 

In that question, if the map size is made responsive with the browser window, then resizing the window does make the features reappear: https://codepen.io/anon/pen/PEqdaj

So the conditions to trigger this bug are:
1. Use vector layers (Rectangles in that question, probably Circle Markers in your case) on an SVG Renderer (by default).
2. Remove the SVG Renderer from the map (typically using `map.eachLayer(function(layer) {map.removeLayer(layer)})`).
3. Re-add some vector layers, on the same SVG Renderer (default behaviour). The SVG Renderer is automatically re-used and re-added onto the map by Leaflet, but it no longer has specified `width` and `height` attributes, making it invisible.
4. When the viewport size is changed (e.g. resizing the browser window if the viewport depends on window size), the SVG Renderer size changes, calling its `_update` method and re-assigning `width` and `height` attributes. The Renderer reappears (and the features drawn on it).

I have included several easy workaround on the SO post that should work for your case as well, before the bug is permanently fixed here and a new version is published.

However, should none of them work in your situation, then you might have a different case; please include more details and a reproduction example so that it is possible to investigate.

**Comment by ghybs** [comment]
Note: I have edited the title of this issue to match the bug described in the SO post, since I believe it applies to your case as well.

However, if that is not the case, please open a different issue.

**Comment by abigaildelarosa** [comment]
Hi, 

ghybs thats exactly my case and its not me, neither someone of my team, but thank you so much for give me an extra insight of it.
