### ISSUE TITLE
import * as L from 'leaflet' gets "Can't resolve 'leaflet'" with 1.8.0-beta0

### ISSUE THREAD

**Issue by VashJuan** [Leaflet/Leaflet#8053]
**Steps to reproduce**

I have an 'evergreen' Angular app (https://github.com/EOCOnline/rangertrak)
It compiled fine (& runs with known issues), in VSCode, using "ng s -o" with (with leaflet 1.7.1)
Then I run `npm install leaflet@1.8.0-beta.0` and now running `ng s -o` gets:

```
./src/app/entry/mini-lmap.component.ts:3:0-29 - Error: Module not found: Error: Can't resolve 'leaflet' in 'D:\Projects\RangerTrak\rangertrak\src\app\entry'
```

(which is yelling me about `import * as L from 'leaflet'`)

```
./src/app/lmap/lmap.component.ts:2:0-31 - Error: Module not found: Error: Can't resolve 'leaflet' in 'D:\Projects\RangerTrak\rangertrak\src\app\lmap'

./node_modules/leaflet/dist/leaflet-src.js - Error: Module build failed (from ./node_modules/source-map-loader/dist/cjs.js):
Error: ENOENT: no such file or directory, open 'D:\Projects\RangerTrak\rangertrak\node_modules\leaflet\dist\leaflet-src.js'
```

Restarting VSCode, I get it to compile without any obvious errors, but on running I get:
<img width="395" alt="3-12-2022 at 7 59 28 AM" src="https://user-images.githubusercontent.com/8594671/158025431-e8506118-9237-4a67-8757-82cbc5892d46.png">

I'm no expert on this and this could well be user error or due to other packages installed (FEEL FREE TO CLOSE THIS ISSUE if so!), but I thought you might want the feedback. I do not need any of the new features, so am happy retreating to 1.7.1 for now.

I'm super impressed at your great work, and dismayed at the war. Our hearts are with you.

**Expected behavior**

**Current behavior**

**Environment**
- Leaflet version:
- Browser (with version):
- OS/Platform (with version):

PS:
```
D:\Projects\RangerTrak\rangertrak> npm list
rangertrak@0.11.38 D:\Projects\RangerTrak\rangertrak
├── __ngcc_entry_points__.json@ extraneous
├── @angular-devkit/build-angular@13.2.6
├── @angular-material-components/color-picker@7.0.1
├── @angular-material-components/datetime-picker@7.0.1
├── @angular/animations@13.2.6
├── @angular/cdk@13.2.6
├── @angular/cli@13.2.6
├── @angular/common@13.2.6
├── @angular/compiler-cli@13.2.6
├── @angular/compiler@13.2.6
├── @angular/core@13.2.6
├── @angular/fire@7.2.1
├── @angular/flex-layout@13.0.0-beta.38
├── @angular/forms@13.2.6
├── @angular/google-maps@13.2.6
├── @angular/material@13.2.6
├── @angular/platform-browser-dynamic@13.2.6
├── @angular/platform-browser@13.2.6
├── @angular/router@13.2.6
├── @angular/service-worker@13.2.6
├── @fortawesome/fontawesome-svg-core@1.3.0
├── @fortawesome/free-brands-svg-icons@6.0.0
├── @fortawesome/free-regular-svg-icons@6.0.0
├── @fortawesome/free-solid-svg-icons@6.0.0
├── @googlemaps/markerclusterer@1.0.26
├── @material/banner@13.0.0
├── @material/slider@13.0.0
├── @material/switch@13.0.0
├── @mdi/js@6.5.95
├── @ngx-pwa/local-storage@13.0.2
├── @popperjs/core@2.11.2
├── @types/google-maps@3.2.3
├── @types/google.maps@3.48.2
├── @types/jasmine@3.10.3
├── @types/leaflet.markercluster@1.4.6
├── @types/leaflet@1.7.9
├── @types/node@17.0.21
├── @types/supercluster@7.1.0
├── @what3words/api@4.0.5
├── ag-grid-angular@27.0.0
├── ag-grid-community@27.0.1
├── chalk@4.1.2
├── cross-conf-env@1.2.1
├── dayjs@1.10.8
├── dev-norms@1.7.1
├── firebase@9.6.8
├── http-server@14.1.0
├── idb@7.0.0
├── import-sort-cli@6.0.0
├── import-sort-parser-typescript@6.0.0
├── import-sort-style-module@6.0.0
├── import-sort@6.0.0
├── init-dev-env@1.0.0
├── jasmine-core@4.0.1
├── js-beautify@1.14.0
├── jshint@2.13.4
├── karma-chrome-launcher@3.1.1
├── karma-coverage@2.2.0
├── karma-jasmine-html-reporter@1.7.0
├── karma-jasmine@4.0.1
├── karma@6.3.17
├── leaflet.markercluster@1.5.3
├── leaflet.offline@2.1.0
├── leaflet@1.8.0-beta.0
├── npm-run-all@4.1.5
├── prettier@2.5.1
├── rimraf@3.0.2
├── rxfire@6.0.3
├── rxjs@7.5.5
├── tslib@2.3.1
├── tslint-config-prettier@1.18.0
├── tslint-etc@1.13.10
├── tslint-plugin-prettier@2.3.0
├── tslint@6.1.3
├── tsviz-cli@2.0.3
├── typescript@4.5.5
├── xlsx-style@0.8.13
├── xlsx@0.18.3
└── zone.js@0.11.5
```

on a desktop with Windows 10 & latest Chrome browser

**Comment by IvanSanchez** [comment]
I usually have a strict policy about compatibility bugs with frameworks, but this one is actually written in a helpful way, and relates to the ongoing problems about (re)packaging Leaflet 1.8.0.

The important bit of information here is:

```
Error: ENOENT: no such file or directory, open 'D:\Projects\RangerTrak\rangertrak\node_modules\leaflet\dist\leaflet-src.js'
```

However, `leaflet-src.js` does exist in the 1.8.0-beta0 release as NPM package, as can be seen in https://unpkg.com/browse/leaflet@1.8.0-beta.0/dist/ . 

@VashJuan Can you please double-check the contents of your `D:\Projects\RangerTrak\rangertrak\node_modules\leaflet\dist\` directory, and compare that with the contents of the published NPM package (from https://registry.npmjs.org/leaflet/-/leaflet-1.8.0-beta.0.tgz )?

**Comment by VashJuan** [comment]
Oh ya. I think I failed to install things properly, as I've got the OLD files in my node_modules directory. 

I'll play/investigate a bit more & get back. THANKS!

![image](https://user-images.githubusercontent.com/8594671/158027336-6773746f-950c-433c-b5a2-aa7620add31f.png)

**Comment by VashJuan** [comment]
The original errors persist.

(My very last note was my mistake:
I spelled the package name wrong after having gone back to 1.7.1: 
install leaflet@1.8.0-beta0, NOT 
install leaflet@1.8.0-beta.0)

Just now, I did install leaflet@1.8.0-beta.0, and a diff shows no differences between 
\node_modules\leaflet\ and 
leaflet-1.8.0-beta.0\package\
so it does look like the installer worked fine, and I am getting the original error again.

I'll poke around a bit more, to see if I can figure out a resolution...

**Comment by Eschon** [comment]
Since the error you show is with the `leaflet.noConflict = function () {`, this might be the same problem as in #8048 if so, it should already be fixed with #8050

**Comment by BButner** [comment]
> @VashJuan can you verify that this problem has been addressed in the latest version on `main`? I believe that this might indeed be a duplicate of #8048.

Is there a way I can easily install `main` into my own project to test here? Running in to the exact same issue...

**Comment by VashJuan** [comment]
That's partially my confusion too:
If I do:
`npm install leaflet@1.8.0-beta.0`
do I get the nightly build or something from a week or so back (pre-the hopeful fix).

(In my case I broke something else on my end and am still trying to get back where I can test your 'fix'. Sorry for my delay.)

**Comment by VashJuan** [comment]
I'm doing Angular & Typescript, & have incorporated leaflet.MarkerCluster & leaflet.offline. I think I've uninstalled & removed then from package.json, angular.json, then added the ref to the main script from the Amazon CDN, and still get 
"Cannot find module 'leaflet' or its corresponding type declarations.ts(2307)" when I try to do either:
`import * as L from 'leaflet'`
`import { tileLayer, latLng, control, marker, icon, divIcon, LatLngBounds, Map, MapOptions, MarkerClusterGroup, MarkerClusterGroupOptions } from 'leaflet'`

I easily could have missed something as there are a bunch of potential pitfalls, so will await the next beta & re-verify this still exists then. (As I noted I'm not reliant on any new functionality, just trying to help test - so certainly don't want to waste your time either!)

**Comment by BButner** [comment]
> I'm doing Angular & Typescript, & have incorporated leaflet.MarkerCluster & leaflet.offline.
> 
> I think I've uninstalled & removed them from package.json, angular.json, uninstalled the @type files, then added the ref to the main script from the Amazon CDN, and still get `"Cannot find module 'leaflet' or its corresponding type declarations.ts(2307)"` when I try to do either: `import * as L from 'leaflet'` or `import { tileLayer, latLng, control, marker, icon, divIcon, LatLngBounds, Map, MapOptions } from 'leaflet'`
> 
> I easily could have missed something as there are a bunch of potential pitfalls, so will await the next beta & re-verify this still exists then. (As I noted I'm not reliant on any new functionality, just trying to help test - so certainly don't want to waste your time either!)

Its much easier to just clone the project, run 'npm install', then do 'npm run build', then run 'npm link' from the root of the project directory, then go into your project and to 'npm link leaflet'.

I did this, and was able to resolve the issue originally in this issue, and resolve the issue I was originally experiencing that was making me want to update.

**Comment by turbolego** [comment]
@BButner thanks! ❤️ 
I did `npm run build`, then `npm link` and `npm link leaflet` from the root of the project directory.
After doing this, i no longer had error messages related to proj4leaflet and @asymmetrik/ngx-leaflet-markercluster

However, if i run:
`rimraf node_modules/ && rimraf package-lock.json && npm i && npm run build`

I get the errors related to proj4leaflet and @asymmetrik/ngx-leaflet-markercluster again, and i have to run `npm link` and `npm link leaflet` for the errors to go away. Seems link i just have to add `npm link` and `npm link leaflet` every time? 😆 

```
./src/assets/utilities/NVDBCRS.ts:4:37-47 - Error: export 'Proj' (imported as 'L') was not found in 'leaflet' (possible exports: Bounds, Browser, CRS, Canvas, Circle, CircleMarker, Class, Control, DivIcon, DivOverlay, DomEvent, DomUtil, Draggable, Evented, FeatureGroup, GeoJSON, GridLayer, Handler, Icon, ImageOverlay, LatLng, LatLngBounds, Layer, LayerGroup, LineUtil, Map, Marker, Mixin, Path, Point, PolyUtil, Polygon, Polyline, Popup, PosAnimation, Projection, Rectangle, Renderer, SVG, SVGOverlay, TileLayer, Tooltip, Transformation, Util, VideoOverlay, bind, bounds, canvas, circle, circleMarker, control, default, divIcon, extend, featureGroup, geoJSON, geoJson, gridLayer, icon, imageOverlay, latLng, latLngBounds, layerGroup, map, marker, noConflict, point, polygon, polyline, popup, rectangle, setOptions, stamp, svg, svgOverlay, tileLayer, tooltip, transformation, version, videoOverlay)
```
```
./node_modules/@asymmetrik/ngx-leaflet-markercluster/fesm2015/asymmetrik-ngx-leaflet-markercluster.mjs:20:32-52 - Error: export 'markerClusterGroup' (imported as 'L') was not found in 'leaflet' (possible exports: Bounds, Browser, CRS, Canvas, Circle, CircleMarker, Class, Control, DivIcon, DivOverlay, DomEvent, DomUtil, Draggable, Evented, FeatureGroup, GeoJSON, GridLayer, Handler, Icon, ImageOverlay, LatLng, LatLngBounds, Layer, LayerGroup, LineUtil, Map, Marker, Mixin, Path, Point, PolyUtil, Polygon, Polyline, Popup, PosAnimation, Projection, Rectangle, Renderer, SVG, SVGOverlay, TileLayer, Tooltip, Transformation, Util, VideoOverlay, bind, bounds, canvas, circle, circleMarker, control, default, divIcon, extend, featureGroup, geoJSON, geoJson, gridLayer, icon, imageOverlay, latLng, latLngBounds, layerGroup, map, marker, noConflict, point, polygon, polyline, popup, rectangle, setOptions, stamp, svg, svgOverlay, tileLayer, tooltip, transformation, version, videoOverlay)

```

My setup:
```
"@angular-devkit/schematics": "13.3.1",
"@angular/animations": "13.3.2",
"@angular/cdk": "13.3.2",
"@angular/common": "13.3.2",
"@angular/compiler": "13.3.2",
"@angular/core": "13.3.2",
"@angular/forms": "13.3.2",
"@angular/material": "13.3.2",
"@angular/material-moment-adapter": "13.3.2",
"@angular/platform-browser": "13.3.2",
"@angular/platform-browser-dynamic": "13.3.2",
"@angular/router": "13.3.2",
"@arcgis/core": "4.23.7",
"@asymmetrik/ngx-leaflet": "13.0.2",
"@asymmetrik/ngx-leaflet-markercluster": "13.0.1",
"@turf/turf": "6.5.0",
"@types/leaflet.markercluster": "1.5.1",
"leaflet": "1.9.0",
"leaflet-polylineoffset": "1.1.1",
"leaflet.markercluster": "1.5.3",
"leaflet": "1.9.0",
"leaflet-polylineoffset": "1.1.1",
"leaflet.markercluster": "1.5.3",
```

**Comment by TrueMoniker** [comment]
I had the same issue when updating from leaflet `1.9.3` to `1.9.4`.
I added `@types/leaflet` (`npm i @types/leaflet`) and that fixed the reference. 
Specifically `@types/leaflet": "^1.9.21",`.

_not sure if this is related, but I'll leave it here for anyone coming across the same problem_
