### ISSUE TITLE
iOS 15.4 controls hidden under tile layer

### ISSUE THREAD

**Issue by siimots** [Leaflet/Leaflet#8068]
Latest iOS 15.4 created strange bug of disappearing controls in Leaflet 1.6.0 when panning around map.

![Half missing controls](https://i.imgur.com/jittFWf.png)

**Expected behavior**
Controls should stay above tile layer

**Current behavior**
Controls get hidden under tile layer when panning around

**Environment**
- Leaflet version: 1.6.0
- Browser (with version): iOS 15.4 Safari 
- OS/Platform (with version): iOS 15.4

**Additional context**
Bug does not appear in Android Chrome or Windows desktop browsers.
Also worked fine in iOS 15.3.x and previous versions.

**Minimal example reproducing the issue**
My app: https://gis.ee/meri/
Video: https://i.imgur.com/Uu6H8pR.mp4

Safari bugs are quite difficult to debug and probably it will get fixed in future iOS.
This bug report is mostly just for information, hopefully Safari gets some bugfixes soon.

**Comment by IvanSanchez** [comment]
Please try with 1.8.0-beta.0.

**Comment by siimots** [comment]
I discovered that problem appears only when there are a lot of div icons.

Same glitches in 1.8.0-beta.0 also.

Maybe 15.4 safari crashes when there are too many dom elements but it was not problem in 15.3 safari.
Safari is frustrating :(

**Comment by TurtIeSocks** [comment]
Any luck with this? Or anything I can help troubleshoot? My issue on React Leaflet was mentioned above includes a minimum codebase to reproduce, if that helps.

**Comment by siimots** [comment]
I guess we have to wait for iOS 15.4.1 not much to do here.
I have submitted bug report at Apple Feedback Assistant.
Maybe you can submit it too with your app url so they know it is problem for many users.

https://feedbackassistant.apple.com/

**Comment by Falke-Design** [comment]
@TurtIeSocks yes we need to wait for the next IOS release. No one of the maintainers has an IOS Phone. If it is a long term problem, we need to look for a solution

**Comment by siimots** [comment]
iOS 15.4.1 did not fix it.

But now I tested with new beta release v1.8.0-beta.3 and now controls don't get hidden under tile layer.
https://github.com/Leaflet/Leaflet/pull/8102 maybe it fixed it?

**Comment by plotaroute** [comment]
We've had a few users reporting this issue too with our route planners, using Safari 15.4 on both desktop and mobile:

Desktop: https://www.plotaroute.com/routeplanner
Mobile: https://www.plotaroute.com/mobile/routeplanner

We haven't been able able to reproduce it though, so it does seem to be very intermittent and dependent on some set of circumstances that we haven't yet been able to identify. 

Any more clues as to what the trigger is or how to workaround the problem? For example, if it's a corrupt zIndex issue, would it be possible to check zIndex of the controls after after the map has been dragged to ensure that it is higher than the zIndex of the tile layer?

**Comment by siimots** [comment]
> Any more clues as to what the trigger is or how to workaround the problem? For example, if it's a corrupt zIndex issue, would it be possible to check zIndex of the controls after after the map has been dragged to ensure that it is higher than the zIndex of the tile layer?

I changed controls z-index to 999999 manually in safari developer tools (usb connection to phone) and controls still stayed under tile layer.

**Comment by siimots** [comment]
Webkit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=238589

**Comment by Falke-Design** [comment]
> We've had a few users reporting this issue too with our route planners, using Safari 15.4 on both desktop and mobile:

@mourner can you test it on your mac?

I tested it with the [example from the tutorial](https://leafletjs.com/SlavaUkraini/examples/layers-control/example.html) on a IPhone and it happened too. 
I didn't find a step by step instructions to reproduce but mostly it happened after zooming fully out and zooming / moving while loading. Maybe we have more luck with debugging on a mac.

**Comment by Malvoz** [comment]
I just want to note that I experienced the same issue on Windows using Chrome in the [`<mapml-viewer>`](https://github.com/Maps4HTML/Web-Map-Custom-Element) component which uses Leaflet, in one of the following experiments: https://maps4html.org/experiments/.

This was about a year ago. I can't reproduce it now, although at the time it was very easily reproducible. I never got around to file a bug report (against that component's repo, couldn't reproduce in Leaflet alone IIRC), and didn't have time to investigate a whole lot. But I'm fairly certain it has nothing to do with `z-index`. I recall thinking it could have something to do with `will-change`, but I would've remembered if that had helped.

Perhaps not a very useful comment, though it is to say that it wasn't always a Safari-only issue. Either it was fixed in Chromium or something in `<mapml-viewer>` changed.

**Comment by TurtIeSocks** [comment]
> > We've had a few users reporting this issue too with our route planners, using Safari 15.4 on both desktop and mobile:
> 
> mourner can you test it on your mac?
> 
> I tested it with the [example from the tutorial](https://leafletjs.com/SlavaUkraini/examples/layers-control/example.html) on a IPhone and it happened too. 
> I didn't find a step by step instructions to reproduce but mostly it happened after zooming fully out and zooming / moving while loading. Maybe we have more luck with debugging on a mac.

I couldn't reproduce on a Mac but back when I first opened the React Leaflet issue, I hooked up a 15.4 iPad to a Mac and opened up the dev tools. My best guess is that the bug/issue is related to the new Cascade Layers.

https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/

You can open up the new layers dev panel and see UI components going in and out as you pan/zoom around a Leaflet map.

**Comment by plotaroute** [comment]
We think we may have found a workaround for this. As it's an intermittent problem we can't be 100% sure, but after adding the following css to the page the problem seemed to go away:

.leaflet-control-container .leaflet-top, .leaflet-control-container .leaflet-bottom {
	transform: translate3d(0px, 0px, 0px);
}

We have a few other DOM elements (outside of the leaflet map container) that are positioned above the map, so we had to add the same transform css for these too.

**Comment by siimots** [comment]
Thank you!

@plotaroute, can you make PR for it. I think it great simple fix.
Looks like there will be 1.8.0 release soon, so it would be nice to have it included.

**Comment by Malvoz** [comment]
@Falke-Design from https://github.com/Leaflet/Leaflet/discussions/8044#discussioncomment-2539739:
https://dev.opera.com/articles/css-will-change-property/#the-old-the-translatez-or-translate3d-hack

**Comment by Falke-Design** [comment]
@Malvoz Thank you! I searched 15 minutes ... 😄 

@plotaroute can you please try to use:
```
will-change: transform;
```

**Comment by Jmuccigr** [comment]
will-try. Can you confirm that I should be inserting this bit of css then:

```
.leaflet-control-container .leaflet-top, .leaflet-control-container .leaflet-bottom {
  will-change: transform;
 }
```

**Comment by Falke-Design** [comment]
yes exactly

**Comment by Jmuccigr** [comment]
Yeah, that seems to work, too. Here's exactly what I added:

```
.leaflet-control-container .leaflet-top, .leaflet-control-container .leaflet-bottom {
  will-change: transform;
 }
```

**Comment by Malvoz** [comment]
The [WebKit bug](https://github.com/Leaflet/Leaflet/issues/8068#issuecomment-1088521297) was fixed 2022-04-20.

Confirmed workarounds include:
- [`transform: translate3d(0, 0, 0)`](https://github.com/Leaflet/Leaflet/issues/8068#issuecomment-1099073652)
- [`will-change: transform`](https://github.com/Leaflet/Leaflet/issues/8068#issuecomment-1099207299)

`transform: translate(0)` may also work.

(whether they should rather be applied to `.leaflet-top, .leaflet-right, .leaflet-bottom, .leaflet-left` or directly on `.leaflet-control-container` I can't test myself.)

**Comment by Falke-Design** [comment]
> The [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=238589) (https://github.com/Leaflet/Leaflet/issues/8068#issuecomment-1088521297) was fixed 2022-04-20.

@Malvoz I suggest to add https://github.com/Leaflet/Leaflet/labels/won%27t%20fix, what do you think?

**Comment by simonneutert** [comment]
@Falke-Design thank you very much for the hint given 🚀 
It fixed the disappearing overlays and buttons I had to struggle with  👏

**Comment by Malvoz** [comment]
> iOS 15.5 was just released and it did not fix this problem.

File a new WebKit bug? Or ask in the existing one?

> Maybe css will-change fix is needed in Leaflet CSS?

Simultaneously people are asking to [remove `will-change`](https://github.com/Leaflet/Leaflet/pull/7872).

**Comment by aabdolla** [comment]
If it is removed from the tiles then will we not need to add it to the controls?

**Comment by siimots** [comment]
> > iOS 15.5 was just released and it did not fix this problem.
> 
> File a new WebKit bug? Or ask in the existing one?
> 
> > Maybe css will-change fix is needed in Leaflet CSS?
> 
> Simultaneously people are asking to [remove `will-change`](https://github.com/Leaflet/Leaflet/pull/7872).

Leaflet has fixes for IE8-10, but why not make fixes for millions of iOS devices?
Safari is new IE. This bug has been there for 9 months and it does not look there will be any proper fix in sight.
Safari does not auto update from App Store. iOS update is needed, but many users skip those big updates.
It means Leaflet will be broken for long time for many users.

**Comment by Malvoz** [comment]
> iOS 15.5 was just released and it did not fix this problem.

@siimots Is it fixed in 15.6? Otherwise you may want to re-open your [original bug](https://bugs.webkit.org/show_bug.cgi?id=238796) that was marked as duplicate of bug 238589.

> It means Leaflet will be broken for long time

AFAICT (and as described in the bug report) the bug is only appearing during pan, so it's not totally broken, more of a UX bug. Anyway, even if the workaround was added to leaflet.css it wouldn't be fixed until the next release.

If you still think it is needed, feel free to send a PR and we can re-evaluate. I think we should use the [`@supports`](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) CSS at-rule to [target Safari only](https://caniuse.com/mdn-css_properties_-webkit-touch-callout), e.g.:

```css
/* Safari bug fix for #8068. */
@supports (-webkit-touch-callout: none) {
  .leaflet-control-container .leaflet-top,
  .leaflet-control-container .leaflet-bottom {
    will-change: transform;
  }
}
```

**Comment by siimots** [comment]
I'm using iOS 16 beta and this bug is fixed there.

I do not have access to 15.x device at the moment.

**Comment by jonkoops** [comment]
Thanks for verifying that @siimots, much appreciated.

**Comment by cgalvarino** [comment]
FYI I see this issue in Chrome v 104.x on the iPhone running iOS 15.5.  https://github.com/Leaflet/Leaflet/issues/8068#issuecomment-1107640526 does the trick.  H/T!

**Comment by cgalvarino** [comment]
> FYI I see this issue in Chrome v 104.x on iPhone running iOS 15.5. [#8068 (comment)](https://github.com/Leaflet/Leaflet/issues/8068#issuecomment-1107640526) does the trick. H/T!

I spoke too soon.  Didn't seem to fix it completely.  I'll stay tuned for the iOS update.

**Comment by Lipomoea** [comment]
I encountered something similar. The cross marker is supposed to be above the geojson layer but now it's below. Only appear on webkit (rather than chromium) kernel I suppose.

<img width="474" height="418" alt="Image" src="https://github.com/user-attachments/assets/1d8f1b3e-842e-4c9e-9c57-caabf250cfaa" />
